#!/usr/bin/env bash

set -eou pipefail

# https://github.com/ibireme/yyjson/pull/235
yyjson_version="7b57844402efddbb7c92cdeb5066842fb0c60e01"

curl -Ls -o include/yyjson/yyjson.c "https://raw.githubusercontent.com/ibireme/yyjson/${yyjson_version}/src/yyjson.c"
curl -Ls -o include/yyjson/yyjson.h "https://raw.githubusercontent.com/ibireme/yyjson/${yyjson_version}/src/yyjson.h"

sed -i 's/yyjson_api_inline void yyjson_doc_free/yyjson_api void yyjson_doc_free/g' include/yyjson/yyjson.h
sed -i 's/if (pre)/if (false)/g' include/yyjson/yyjson.c
sed -i 's/unlikely(pos == src)/false/g' include/yyjson/yyjson.c
sed -i 's/#define YYJSON_READER_DEPTH_LIMIT 0/#define YYJSON_READER_DEPTH_LIMIT 1024/g' include/yyjson/yyjson.c
